MvcCoreExamenMauricio/Models/Comic.cs
namespace MvcCoreExamenMauricio.Models
{
    public class Comic
    {
        public int IdComic { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public string Descripcion { get; set; }
    }
}

MvcCoreExamenMauricio/Models/ErrorViewModel.cs
namespace MvcCoreExamenMauricio.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreExamenMauricio/Controllers/ComicsController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreExamenMauricio.Models;
using MvcCoreExamenMauricio.Repositories;

namespace MvcCoreExamenMauricio.Controllers
{
    public class ComicsController : Controller
    {
        private IRepositoryComics repo;

        public ComicsController(IRepositoryComics repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            List<Comic> comics = this.repo.GetAllComics();
            return View(comics);
        }

        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Crear(Comic comic)
        {
            this.repo.InsertComic(comic.Nombre, comic.Imagen, comic.Descripcion);
            return RedirectToAction("Index");
        }

        public IActionResult CrearSP()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CrearSP(Comic comic)
        {
            this.repo.InsertComicSP(comic.Nombre, comic.Imagen, comic.Descripcion);
            return RedirectToAction("Index");
        }

        public IActionResult DatosComic()
        {
            ViewData["COMICS"] = this.repo.GetAllComics();
            return View();
        }
        [HttpPost]
        public IActionResult DatosComic(int idcomic)
        {
            ViewData["COMICS"] = this.repo.GetAllComics();
            Comic comic = this.repo.FindComicById(idcomic);
            return View(comic);
        }

        public IActionResult Delete(int idcomic)
        {
            Comic comic = this.repo.FindComicById(idcomic);
            return View(comic);
        }

        public IActionResult DeleteConfirm(int idcomic)
        {
            this.repo.DeleteComicById(idcomic);
            return RedirectToAction("Index");
        }
    }
}

MvcCoreExamenMauricio/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreExamenMauricio.Models;
using System.Diagnostics;

namespace MvcCoreExamenMauricio.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreExamenMauricio/Views/Comics/Crear.cshtml
<h1>Nuevo Comic</h1>

<p>
    <a asp-controller="Comics"
       asp-action="Index">
        Back to Index
    </a>
</p>

<form method="post">
    <label>Nombre</label>
    <input type="text" name="nombre" class="form-control" />
    <label>Imagen</label>
    <input type="text" name="imagen" class="form-control" />
    <label>Descripción</label>
    <input type="text" name="descripcion" class="form-control" />
    <button class="btn btn-info">
        Crear Comic
    </button>
</form>

MvcCoreExamenMauricio/Views/Comics/CrearSP.cshtml
<h1>Nuevo Comic Procedure</h1>

<p>
    <a asp-controller="Comics"
       asp-action="Index">
        Back to Index
    </a>
</p>

<form method="post">
    <label>Nombre</label>
    <input type="text" name="nombre" class="form-control" />
    <label>Imagen</label>
    <input type="text" name="imagen" class="form-control" />
    <label>Descripción</label>
    <input type="text" name="descripcion" class="form-control" />
    <button class="btn btn-info">
        Crear Comic
    </button>
</form>

MvcCoreExamenMauricio/Views/Comics/DatosComic.cshtml
@model Comic
@{
    List<Comic> comics = (List<Comic>)ViewData["COMICS"];
}
<h1>Datos comic</h1>
<form method="post">
    <label>Especialidad</label>
    <select class="form-select" name="idcomic">
        @foreach (Comic com in comics)
        {
            <option value="@com.IdComic">@com.Nombre</option>
        }
    </select>
    <button class="btn btn-warning">Buscar Comic</button>
</form>
@if (Model != null)
{
    <ul class="list-group">
        <li class="list-group-item">@Model.IdComic</li>
        <li class="list-group-item">@Model.Nombre</li>
        <li class="list-group-item"><img src="@Model.Imagen" style="width:100px;height:100px;"/></li>
        <li class="list-group-item">@Model.Descripcion</li>
    </ul>
}

MvcCoreExamenMauricio/Views/Comics/Delete.cshtml
@model Comic
<h1>¿Estás seguro de que deseas borrar el siguiente cómic?</h1>
<ul class="list-group">
    <li class="list-group-item">@Model.IdComic</li>
    <li class="list-group-item">@Model.Nombre</li>
    <li class="list-group-item"><img src="@Model.Imagen" style="width:100px;height:100px;" /></li>
    <li class="list-group-item">@Model.Descripcion</li>
</ul>
<a asp-action="DeleteConfirm" asp-controller="Comics" asp-route-idcomic="@Model.IdComic" class="btn btn-danger">Borrar</a>
<a asp-action="Index" asp-controller="Comics" class="btn btn-info">Cancelar</a>

MvcCoreExamenMauricio/Views/Comics/Index.cshtml
@model List<Comic>

<h1>Comics</h1>

<p>
    <a asp-controller="Comics" asp-action="Crear">
        Crear nuevo comic
    </a>
</p>
<p>
    <a asp-controller="Comics" asp-action="CrearSP">
        Crear nuevo comic Procedure
    </a>
</p>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Imagen</th>
            <th>Descripción</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Comic com in Model)
        {
            <tr>
                <td>@com.Nombre</td>
                <td><img src="@com.Imagen" style="width:100px;height:100px;"/></td>
                <td>@com.Descripcion</td>
                <td><a class="btn btn-danger" asp-controller="Comics" asp-action="Delete" asp-route-idcomic="@com.IdComic">Eliminar</a></td>
            </tr>
        }
    </tbody>
</table>

MvcCoreExamenMauricio/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreExamenMauricio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreExamenMauricio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreExamenMauricio.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreExamenMauricio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Comics" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Comics" asp-action="DatosComic">Datos Comic</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcCoreExamenMauricio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>